# Generated by Django 4.0.4 on 2022-05-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
