# Generated by Django 4.0.4 on 2022-05-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_issue_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
