# Generated by Django 4.0.4 on 2022-05-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_issue_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.comment'),
        ),
    ]
