# Generated by Django 4.0.4 on 2022-05-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_issue_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project_name',
        ),
        migrations.AddField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project'),
        ),
    ]
