# Generated by Django 4.0.4 on 2022-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_issue_project_name_issue_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='project_id',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
