# Generated by Django 4.0.4 on 2022-05-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_comment_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(default='To Do', max_length=200),
        ),
    ]
